name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        # إذا كان requirements.txt في جذر المشروع
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        # إذا كان requirements.txt داخل مجلد myproject/
        if [ -f myproject/requirements.txt ]; then pip install -r myproject/requirements.txt; fi

    - name: Run migrations
      run: |
        python myproject/manage.py makemigrations --settings=myproject.settings_test
        python myproject/manage.py migrate --settings=myproject.settings_test

    - name: Run Django Tests
      run: |
        python myproject/manage.py test cours --settings=myproject.settings_test --verbosity=2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
          # استخدم Dockerfile الموجود في myproject/
           docker build -f myproject/Dockerfile -t django-app .


    - name: Run Docker Container
      run: |
        docker run -d -p 8000:8000 --name django-app-test django-app
        sleep 10
        docker ps -a

    - name: Deploy to Render
      run: |
        curl -X POST "https://api.render.com/deploy/srv-d4k83sbuibrs73fatdt0?key=rnd_q3BUcT9zhiOIuzP0YlaPgXUnyZqJ"
